import uuid
from datetime import datetime, timezone

services = [
    {
        "uid": uuid.uuid4(),
        "name": "Haircut",
        "description": "Basic haircut for men and women",
        "category": "Hair",
        "duration_minutes": 30,
        "price": 15.0,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "uid": uuid.uuid4(),
        "name": "Beard Trim",
        "description": "Trim and shape your beard",
        "category": "Grooming",
        "duration_minutes": 15,
        "price": 10.0,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "uid": uuid.uuid4(),
        "name": "Hair Coloring",
        "description": "Full hair coloring service",
        "category": "Hair",
        "duration_minutes": 90,
        "price": 50.0,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "uid": uuid.uuid4(),
        "name": "Shampoo & Blow Dry",
        "description": "Hair wash with blow dry",
        "category": "Hair",
        "duration_minutes": 45,
        "price": 20.0,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "uid": uuid.uuid4(),
        "name": "Facial",
        "description": "Relaxing facial treatment",
        "category": "Skin Care",
        "duration_minutes": 60,
        "price": 40.0,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
]
