"""add reviews and payments tables

Revision ID: 6dd280bf5d49
Revises: f323626ea0ea
Create Date: 2026-03-14 22:49:15.233554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dd280bf5d49'
down_revision: Union[str, Sequence[str], None] = 'f323626ea0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('barbershop_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['barbershop_id'], ['barbershops.uid'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('uid')
    )
    op.create_unique_constraint(None, 'barbershops', ['uid'])
    op.create_unique_constraint(None, 'bookings', ['uid'])
    op.create_unique_constraint(None, 'schedules', ['uid'])
    op.create_unique_constraint(None, 'services', ['uid'])
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'schedules', type_='unique')
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_constraint(None, 'barbershops', type_='unique')
    op.drop_table('reviews')
    op.drop_table('payments')
    # ### end Alembic commands ###
