"""add is_verified to users

Revision ID: f99ca7a30f03
Revises: 6dd280bf5d49
Create Date: 2026-04-04 23:51:05.742571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f99ca7a30f03'
down_revision: Union[str, Sequence[str], None] = '6dd280bf5d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['uid'])
    op.create_unique_constraint(None, 'reviews', ['uid'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
